name: darb_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dash_chat_2: ^0.0.20
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  get_storage: ^2.1.1
  supabase_flutter: ^2.3.4
  intl: ^0.18.1
  flutter_otp_text_field: ^1.1.0+2
  otp_timer_button: ^1.1.1
  timer_button: ^2.1.1
  device_preview: ^1.1.0
  font_awesome_flutter: ^10.7.0
  shape_of_view_null_safe: ^3.0.0
  flutter_localization: ^0.2.0
  dropdown_button2: ^2.3.9
  easy_stepper: ^0.8.3
  google_maps_flutter: ^2.2.8
  flutter_chat_ui: ^1.6.12
  file_picker: ^8.0.0+1
  image_picker: ^1.1.0
  open_filex: ^4.4.0
  email_validator: '^2.1.16'
  regexed_validator: ^2.0.0+1
  timeago: ^3.6.1
  permission_handler: ^11.3.1
  google_maps_place_picker_mb: ^3.1.2
  internet_connection_checker_plus: ^2.3.0
  cached_network_image: ^3.3.1
  cron: ^0.6.0
  geolocator: ^10.1.1
  flutter_polyline_points: ^2.0.0
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    - family: InknutAntiqua
      fonts:
        - asset: assets/fonts/InknutAntiqua-Light.ttf
          weight: 300
        - asset: assets/fonts/InknutAntiqua-Regular.ttf
          weight: 400
        - asset: assets/fonts/InknutAntiqua-Medium.ttf
          weight: 500
        - asset: assets/fonts/InknutAntiqua-Bold.ttf
          weight: 700
        - asset: assets/fonts/InknutAntiqua-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InknutAntiqua-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InknutAntiqua-Black.ttf
          weight: 900